domains:
  # Germany Primary
  - ip: 176.9.67.43
    common_name: "TRAEFIK DEFAULT CERT"
  # Germany Failover
  - ip: 178.63.30.122
    common_name: "TRAEFIK DEFAULT CERT"
  # Finland Primary
  - ip: 95.217.100.51
    common_name: "TRAEFIK DEFAULT CERT"
  # Finland Failover
  - ip: 95.216.30.44
    common_name: "TRAEFIK DEFAULT CERT"
  # EnableIT Puppet
  - ip: 95.216.10.96
    common_name: "puppet.enableit.dk"
